Remove helm dependency from e2e test suite
dapr/cli pull request #1131
Opened 2022-11-17 06:58 UTC by shubham1172

Signed-off-by: Shubham Sharma <shubhash@microsoft.com>

# Description

Remove dependency from Helm since it's no longer available in the latest macOS

## Issue reference

Please reference the issue this PR will close: #1130 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2022-11-17 07:15 UTC, mukundansundar requested changes
can this be done for the dashboard check as well ?

2022-11-17 07:19 UTC, shubham1172 commented
> can this be done for the dashboard version as well ?

Yes indeed, good idea. Note that it was earlier taking the version from 1.9.0's helm charts. Now it's pointing to the latest.

2022-11-17 07:43 UTC, mukundansundar commented
> > can this be done for the dashboard version as well ?
> 
> Yes indeed, good idea. Note that it was earlier taking the version from 1.9.0's helm charts. Now it's pointing to the latest.

Good point. Is there any scenario where the latest version will not be in the latest Dapr runtime version also? 

Also what happens with RC releases with this command?

2022-11-17 07:45 UTC, shubham1172 commented
> Good point. Is there any scenario where the latest version will not be in the latest Dapr runtime version also?

It is safe to assume that we will always make that change. It's a part of our endgame check-list too.

> Also what happens with RC releases with this command?

The sorting is done correctly even with RCs using sed magic.

2022-11-17 08:12 UTC, mukundansundar commented
it would really be nice if podman becomes a default with macOS :)

2022-11-17 19:20 UTC, pravinpushkar approved these changes

2022-11-18 03:29 UTC, shubham1172 commented
@mukundansundar can we merge it?

2022-11-18 05:35 UTC, mukundansundar approved these changes

2022-11-18 05:35 UTC, merged