Make app id unique across apps started by dapr run
dapr/cli pull request #1197
Opened 2023-02-01 10:34 UTC by pravinpushkar

Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

# Description

- Make appID unique across apps started by dapr run.
- dapr run -f will exit completely if AppIDs are not unique in `dapr.yaml`

2023-02-01 10:41 UTC, shubham1172 submitted a review, later dismissed
Small nit

2023-02-01 10:41 UTC, shubham1172 commented on pkg/standalone/run.go
> +		return fmt.Errorf("invalid configuration for AppID. App id %q is not available", config.AppID)
```suggestion
		return fmt.Errorf("invalid configuration for appID. App ID %q is already in use", config.AppID)
```

2023-02-01 10:56 UTC, mukundansundar requested changes
add a test with normal run as well, running an app with app id and the next run `executeWhileRunning` should fail.

Change it to point to `release-1.10`

2023-02-01 13:20 UTC, mukundansundar submitted a review, later dismissed
lgtm

2023-02-01 13:35 UTC, shubham1172 approved these changes

2023-02-01 13:48 UTC, mukundansundar commented
AppID uniqueness was unintentionally removed in 1.6, and there is no complete support for it yet. Will work on https://github.com/dapr/cli/issues/698 to allow appID duplication.

2023-02-01 14:17 UTC, mukundansundar approved these changes

2023-02-01 14:19 UTC, shubham1172 submitted a review, later dismissed

2023-02-01 17:21 UTC, mukundansundar approved these changes

2023-02-01 17:24 UTC, shubham1172 approved these changes

2023-02-02 04:26 UTC, artursouza approved these changes

2023-02-02 04:56 UTC, pravinpushkar commented
one suggested improvement that can be tried for 1.11 until #698 is implemented - 

> You are checking based on the list of processes. It is not guaranteed but it is better than we have now. This can also be achieved by a file lock, but not sure how to do that on Windows. It can be in 1.11 since it would avoid race conditions.

2023-02-02 05:00 UTC, mukundansundar commented
@yaron2 had some concerns with this PR breaking some of the users and also that this unintentional change has been there from 1.6. 

@yaron2 thoughts on this?

2023-02-02 07:20 UTC, yaron2 commented
> @yaron2 had some concerns with this PR breaking some of the users and also that this unintentional change has been there from 1.6.
> 
> @yaron2 thoughts on this?

Technically, it's not forbidden to run two instances of Dapr with the same app Id - this is what happens naturally on K8s with multiple pods all having the same app Id. So unless there is something in the local dev experience that is degraded by having this, maybe it's best to leave it as is, because:

1. It has been allowed in the CLI for the last 3 releases
2. It allows developers to easily test things like two consumers in a consumer group with pub/sub, and multiple consumers of a distributed Lock
3. There may have been users who use the CLI to bootstrap non containerized envs with Dapr who rely on this, although unlikely.

I feel like we can go either way, but would like to revert this based on something concrete.

2023-02-02 07:40 UTC, pravinpushkar commented
@yaron2 
> Technically, it's not forbidden to run two instances of Dapr with the same app Id - this is what happens naturally on K8s with multiple pods all having the same app Id. So unless there is something in the local dev experience that is degraded by having this, maybe it's best to leave it as is

If we are going to have this as is then we have to correct the `dapr stop` behaviour.
Currently `dapr stop appID` will stop any one of the many instances of apps having same `appID`.
`dapr stop` iterates through the apps list obtained via `dapr list` and exist after getting the 1st match for the provided app ID. 

And similar behaviour happen for `dapr run -f`.

2023-02-02 07:50 UTC, mukundansundar commented
The behavior of the following CLI commands also will be affected right? `dapr stop`, `dapr publish`, `dapr invoke` etc. 
Since all of them use `list` to list the apps and based on the `appID` select a particular app to perform the function of invoke, publish or to stop

2023-02-13 06:11 UTC, mukundansundar commented
@dapr/maintainers-cli Based on the discussions that we have had offline, this change will not be done.

2023-02-13 06:11 UTC, closed without merging