Fix unexpected behaviour in dapr list
dapr/cli pull request #1244
Opened 2023-02-23 14:09 UTC by Taction

# Description

In previous version dapr run puts the `--enable-app-health-check` at the end of the args list, while 1.10 put it in the middle. Below is an example of the command dapr starts daprd.
```
# previous
/root/.dapr/bin/daprd --app-id Watcherswift-Carp --app-port 3000 --dapr-http-port 41309 --dapr-grpc-port 39479 --config /root/.dapr/config.yaml --app-protocol http --profile-port -1 --log-level info --app-max-concurrency -1 --placement-host-address localhost:50005 --components-path /root/.dapr/components --metrics-port 33949 --dapr-http-max-request-size -1 --dapr-http-read-buffer-size -1 --dapr-internal-grpc-port 44463 --enable-app-health-check

#now
/root/.dapr/bin/daprd --config /root/.dapr/config.yaml --app-protocol http --log-level info --app-max-concurrency -1 --placement-host-address localhost:50005 --components-path /root/.dapr/components --dapr-http-max-request-size -1 --dapr-http-read-buffer-size -1 --enable-app-health-check --app-id herogreat-buffalo --app-port 3000 --dapr-http-port 35985 --dapr-grpc-port 43717 --profile-port -1 --metrics-port 46873 --dapr-internal-grpc-port 43069
```

I changed the args parse to fit these flag without params.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1241

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2023-02-23 15:12 UTC, mukundansundar requested changes
@Taction thanks for this quick fix PR. Can you add an E2E for this change? Also please fix the linter errors

2023-02-23 15:33 UTC, Taction commented
Sure, I'll look into the e2e tests.

2023-02-23 17:44 UTC, mukundansundar commented
> Sure, I'll look into the e2e tests.

Thanks!

2023-02-28 16:59 UTC, mukundansundar approved these changes
lgtm

2023-02-28 16:59 UTC, merged