Add --header/-H to dapr invoke
dapr/cli pull request #1287
Opened 2023-05-20 14:48 UTC by hunter007

# Description

to support pass customized headers to dapr app

## Issue reference

https://github.com/dapr/cli/issues/1286

2023-05-22 16:04 UTC, mukundansundar reviewed
@hunter007 Thanks for adding this feature.
Can you add E2E for the this feature please?

2023-05-23 01:04 UTC, hunter007 commented
> @hunter007 Thanks for adding this feature. Can you add E2E for the this feature please?

:)  Review this PR first: https://github.com/dapr/go-sdk/pull/405

2023-05-26 12:53 UTC, mukundansundar commented
> > @hunter007 Thanks for adding this feature. Can you add E2E for the this feature please?
> 
> :) Review this PR first: [dapr/go-sdk#405](https://github.com/dapr/go-sdk/pull/405)

seems the PR has been merged :)

2023-05-26 20:03 UTC, hunter007 commented
> > > @hunter007 Thanks for adding this feature. Can you add E2E for the this feature please?
> > 
> > 
> > :) Review this PR first: [dapr/go-sdk#405](https://github.com/dapr/go-sdk/pull/405)
> 
> seems the PR has been merged :)



> > > @hunter007 Thanks for adding this feature. Can you add E2E for the this feature please?
> > 
> > 
> > :) Review this PR first: [dapr/go-sdk#405](https://github.com/dapr/go-sdk/pull/405)
> 
> seems the PR has been merged :)

Yes,  so the PR could be reviewd.

2023-05-30 16:46 UTC, mukundansundar commented
> > > > @hunter007 Thanks for adding this feature. Can you add E2E for the this feature please?
> > > 
> > > 
> > > :) Review this PR first: [dapr/go-sdk#405](https://github.com/dapr/go-sdk/pull/405)
> > 
> > 
> > seems the PR has been merged :)
> 
> > > > @hunter007 Thanks for adding this feature. Can you add E2E for the this feature please?
> > > 
> > > 
> > > :) Review this PR first: [dapr/go-sdk#405](https://github.com/dapr/go-sdk/pull/405)
> > 
> > 
> > seems the PR has been merged :)
> 
> Yes, so the PR could be reviewd.

Won't the dependency need to be updated to point to the latest go-sdk in this case?

2023-05-31 00:38 UTC, hunter007 commented
> > > > > @hunter007 Thanks for adding this feature. Can you add E2E for the this feature please?
> > > > 
> > > > 
> > > > :) Review this PR first: [dapr/go-sdk#405](https://github.com/dapr/go-sdk/pull/405)
> > > 
> > > 
> > > seems the PR has been merged :)
> > 
> > 
> > > > > @hunter007 Thanks for adding this feature. Can you add E2E for the this feature please?
> > > > 
> > > > 
> > > > :) Review this PR first: [dapr/go-sdk#405](https://github.com/dapr/go-sdk/pull/405)
> > > 
> > > 
> > > seems the PR has been merged :)
> > 
> > 
> > Yes, so the PR could be reviewd.
> 
> Won't the dependency need to be updated to point to the latest go-sdk in this case?

no need.

> > > > > @hunter007 Thanks for adding this feature. Can you add E2E for the this feature please?
> > > > 
> > > > 
> > > > :) Review this PR first: [dapr/go-sdk#405](https://github.com/dapr/go-sdk/pull/405)
> > > 
> > > 
> > > seems the PR has been merged :)
> > 
> > 
> > > > > @hunter007 Thanks for adding this feature. Can you add E2E for the this feature please?
> > > > 
> > > > 
> > > > :) Review this PR first: [dapr/go-sdk#405](https://github.com/dapr/go-sdk/pull/405)
> > > 
> > > 
> > > seems the PR has been merged :)
> > 
> > 
> > Yes, so the PR could be reviewd.
> 
> Won't the dependency need to be updated to point to the latest go-sdk in this case?

No need. https://github.com/dapr/go-sdk/pull/405 is used when writing app with go-sdk. Without https://github.com/dapr/go-sdk/pull/405, `cli invoke` will still send HTTP header by `-H` to dapr app

2023-05-31 05:36 UTC, mukundansundar commented
@hunter007 the specific test that you have written seems to fail `output does not contain "aValue"` ... Can you take a look into this?

2023-06-05 11:56 UTC, hunter007 commented
> @hunter007 the specific test that you have written seems to fail `output does not contain "aValue"` ... Can you take a look into this?

It dependent on dapr/go-sdk which's version is after v1.7.0.

2023-06-07 04:24 UTC, mukundansundar commented
> > @hunter007 the specific test that you have written seems to fail `output does not contain "aValue"` ... Can you take a look into this?
> 
> It dependent on dapr/go-sdk which's version is after v1.7.0.

This PR needs to be modified to use the latest go-sdk then in tests.

2023-06-13 05:23 UTC, mukundansundar commented
@hunter007 1.8 version of go-sdk was released and I believe that needs to be used for the header functionality to work.

2023-06-22 19:07 UTC, hunter007 commented
@mukundansundar github action timeouted, have a retry?

2023-06-23 06:51 UTC, mukundansundar requested changes
small changes please.

2023-06-23 06:51 UTC, mukundansundar commented on cmd/invoke.go
> +	InvokeCmd.Flags().StringArrayVarP(&invokeHeaders, "header", "H", []string{}, "0 or more HTTP Header")
```suggestion
	InvokeCmd.Flags().StringArrayVarP(&invokeHeaders, "header", "H", []string{}, "HTTP headers to be used on invoke")
```

2023-06-23 06:51 UTC, mukundansundar commented on cmd/invoke.go
> +# Invoke a sample method on target app with customized Header
for multiple headers, is it going to be comma separated values?

2023-06-23 06:51 UTC, mukundansundar commented on pkg/standalone/invoke_test.go
> +			name:   "appID found successful invoke with customized header",
please add one test with multiple header values.

2023-07-25 04:17 UTC, closed without merging