Upgrade go to 1.21
dapr/cli pull request #1331
Opened 2023-08-10 09:53 UTC by pravinpushkar

2023-08-17 17:08 UTC, mukundansundar approved these changes

2023-10-26 07:15 UTC, shubham1172 commented
@pravinpushkar could you please resolve the conflicts?

2023-10-31 04:17 UTC, pravinpushkar commented
> @pravinpushkar could you please resolve the conflicts?

yes, I will work on this.

2023-11-29 22:49 UTC, berndverst requested changes
You also need to update the linter version for Go 1.21 support.

In Contrib we are now using v1.55.2. I suggest switching to that version.

https://github.com/dapr/cli/blob/master/.github/workflows/dapr_cli.yaml#L32

You may need to change the golangci-lint configuration and fix some new linter errors. See my PR: https://github.com/dapr/components-contrib/pull/3251

2023-12-14 02:05 UTC, mukundansundar approved these changes

2023-12-19 07:36 UTC, merged