fix perfsprint linter error
dapr/cli pull request #1438
Opened 2024-07-24 03:16 UTC by KentHsu

# Description

Removed `//nolint: perfsprint` directive and fixed all perfsprint linter error

## Issue reference

Please reference the issue this PR will close: #1374

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2025-02-18 16:48 UTC, antontroshin approved these changes

2025-02-26 21:04 UTC, antontroshin requested changes

2025-02-26 21:04 UTC, antontroshin commented on cmd/dashboard.go
> +			webURL := fmt.Sprintf("http://%s", net.JoinHostPort(dashboardHost, strconv.Itoa(portForward.LocalPort)))
```suggestion
			webURL := "http://" + net.JoinHostPort(dashboardHost, strconv.Itoa(portForward.LocalPort))
```

2025-05-08 22:48 UTC, antontroshin commented
@KentHsu could you please apply the suggested change? It'll fix the lint error. TY!

2025-05-13 14:11 UTC, KentHsu commented
Hi @antontroshin , it's updated based on your suggestion. Please let me know if there's other issues blocking this PR. Thank you.

2025-06-12 22:23 UTC, antontroshin approved these changes

2025-06-12 23:12 UTC, closed without merging

2025-11-18 10:12 UTC, marcduiker commented
@holopin-bot @KentHsu Here's a digital badge as a small token of appreciation.