add image pull policy
dapr/cli pull request #1462
Opened 2024-11-12 18:40 UTC by filintod

# Description

Currently one cannot use the kubernetes run when using an image loaded to a kind cluster as the image pull policy is hard coded to Always. This changes it to make it configurable.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2024-11-13 13:23 UTC, filintod commented
@artursouza @antontroshin please check

2024-11-14 00:25 UTC, antontroshin approved these changes

2024-11-14 00:25 UTC, antontroshin commented on pkg/runfileconfig/run_file_config_parser.go
> +			allowedValues := []string{"Always", "Never", "IfNotPresent"}
nit: It might be better to move up as `const` to avoid instantiation on each app and give a meaningful name.

2024-11-14 11:05 UTC, elena-kolevska approved these changes

2024-11-14 14:39 UTC, filintod commented
@antontroshin @elena-kolevska could you re-approved? I added the feedback from @antontroshin

2024-11-14 16:03 UTC, filintod commented
@elena-kolevska please take another look. thx

2024-11-14 16:42 UTC, elena-kolevska requested changes
Linter is failing, but other than that, lgtm

2024-11-14 17:46 UTC, elena-kolevska approved these changes
Super helpful for local development @filintod , thank you very much!

2024-11-15 21:12 UTC, antontroshin approved these changes

2024-12-23 16:50 UTC, yaron2 approved these changes

2024-12-23 20:38 UTC, yaron2 commented
Upgrade tests are failing, is this related?

2025-01-06 18:10 UTC, antontroshin commented
@yaron2 I've re-run the tests, and they all passed, except for regular Podman failure on macOS, which is on my plate for the near future.
IMO, g2g.

2025-01-07 17:09 UTC, merged

2025-01-10 15:54 UTC, marcduiker commented
@holopin-bot @filintod Thanks Filinto!