Changed API logging feature on CLI
dapr/cli pull request #936
Opened 2022-03-29 19:08 UTC by amulyavarote

Signed-off-by: Amulya Varote <amulyavarote@microsoft.com>

# Description

Update api logging feature - Changed from api-log-level to enable-api-logging.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: NA

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2022-03-29 19:24 UTC, mukundansundar commented on README.md
> +In order to set the Dapr runtime API calls log verbosity, use the `enable-api-logging` flag:
```suggestion
In order to set the Dapr runtime to log API calls with `INFO` log verbosity, use the `enable-api-logging` flag:
```

2022-03-29 19:24 UTC, mukundansundar commented on README.md
> +dapr run --app-id nodeapp --app-port 3000 node app.js enable-api-logging true
```suggestion
dapr run --app-id nodeapp --app-port 3000 node app.js enable-api-logging
```
true actually should not be needed, check examples similar to `enable-mtls`

2022-03-29 19:24 UTC, mukundansundar commented on cmd/run.go
> +	RunCmd.Flags().BoolVar(&enableApiLogging, "enable-api-logging", false, "The api calls log verbosity. Valid values are: true or false")
```suggestion
	RunCmd.Flags().BoolVar(&enableApiLogging, "enable-api-logging", false, "Log API calls at INFO verbosity. Valid values are: true or false")
```

2022-03-29 19:24 UTC, mukundansundar commented on tests/e2e/standalone/standalone_test.go
> +		"--enable-api-logging", true,
no need to set `true` ideally...

2022-03-29 19:24 UTC, mukundansundar commented on tests/e2e/standalone/standalone_test.go
> +		"--enable-api-logging", false,
by default false ... so no need to mention that here ...

2022-03-29 19:24 UTC, mukundansundar commented on tests/e2e/standalone/standalone_test.go
>  		"--log-level", "debug",
no need debug log level...

2022-03-29 19:24 UTC, mukundansundar commented on tests/e2e/standalone/standalone_test.go
> -		assert.Contains(t, output, "level=debug msg=\"HTTP API Called: PUT /v1.0/metadata/appCommand\"")
do a negative assertion here

2022-03-30 02:17 UTC, mukundansundar requested changes

2022-03-30 02:17 UTC, mukundansundar commented on tests/e2e/standalone/standalone_test.go
> -		assert.Contains(t, output, "level=debug msg=\"HTTP API Called: PUT /v1.0/metadata/appCommand\"")
do not remove this assert.
Make sure that line is not there in the output. 
Do a negative assertion.

2022-03-30 04:48 UTC, mukundansundar requested changes
@amulyavarote change to release-1.7 branch ....

2022-03-30 06:22 UTC, pravinpushkar approved these changes
LGTM. 
Docs update PR link can be linked.

2022-03-30 06:25 UTC, artursouza approved these changes

2022-03-30 06:57 UTC, mukundansundar approved these changes
lgtm

2022-03-30 06:57 UTC, merged