Bump dev container to 0.1.7
dapr/cli pull request #958
Opened 2022-04-08 09:12 UTC by pravinpushkar

Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

# Description

Bump dev container to 0.1.7
## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: Endgame

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2022-04-08 09:18 UTC, mukundansundar approved these changes

2022-04-08 18:24 UTC, mukundansundar reviewed
@pravinpushkar There have been some changes in the dapr dev container ... Please sync with ItalyPaleAle on that ...

2022-04-08 18:25 UTC, mukundansundar requested changes
change target branch to master and fix commits ...

2022-04-11 16:55 UTC, pravinpushkar commented
Synced with @ItalyPaleAle . There will be few more changes in this PR after https://github.com/dapr/dapr/pull/4499 is merged.

2022-04-18 05:03 UTC, mukundansundar approved these changes

2022-04-18 05:03 UTC, merged